BaoCao_Project/Website/MvcApplication1/Models/HOCONLINE.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MvcApplication1.Models
{
    public class HOCONLINE
    {
        public int ID { get; set; }
        [Display(Name="Tên Web")]
        public string Ten {get;set;}
        [Display(Name="Link")]
        public string Link { get; set; }
        [Display(Name="Hình minh họa")]
        public string Hinh { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}

BaoCao_Project/Website/MvcApplication1/Controllers/HOCONLINEController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;

namespace MvcApplication1.Controllers
{
    [Authorize]
    public class HOCONLINEController : Controller
    {
        private UsersContext db = new UsersContext();


        //
        // GET: /HOCONLINE/
        [AllowAnonymous]
        public ActionResult Index()
        {
            ViewBag.TuyenSinh = db.TUYENSINHs.Take(3).ToList();
            ViewBag.Video = db.VIDEOs.Take(3).ToList();
            ViewBag.BaiHoc = db.BAIHOCs.ToList();
            ViewBag.MonHoc = db.MONHOCs.Take(2).ToList();
            return View(db.HOCONLINEs.ToList());
        }

        //
        // GET: /HOCONLINE/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            HOCONLINE hoconline = db.HOCONLINEs.Find(id);
            if (hoconline == null)
            {
                return HttpNotFound();
            }
            return View(hoconline);
        }

        //
        // GET: /HOCONLINE/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /HOCONLINE/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HOCONLINE hoconline)
        {
            if (ModelState.IsValid)
            {
                db.HOCONLINEs.Add(hoconline);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hoconline);
        }

        //
        // GET: /HOCONLINE/Edit/5
        
        public ActionResult Edit(int id = 0)
        {
            HOCONLINE hoconline = db.HOCONLINEs.Find(id);
            if (hoconline == null)
            {
                return HttpNotFound();
            }
            return View(hoconline);
        }

        //
        // POST: /HOCONLINE/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HOCONLINE hoconline)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hoconline).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hoconline);
        }

        //
        // GET: /HOCONLINE/Delete/5

        public ActionResult Delete(int id = 0)
        {
            HOCONLINE hoconline = db.HOCONLINEs.Find(id);
            if (hoconline == null)
            {
                return HttpNotFound();
            }
            return View(hoconline);
        }

        //
        // POST: /HOCONLINE/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HOCONLINE hoconline = db.HOCONLINEs.Find(id);
            db.HOCONLINEs.Remove(hoconline);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BaoCao_Project/Website/MvcApplication1/Controllers/MONHOCController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;

namespace MvcApplication1.Controllers
{
    public class MONHOCController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /MONHOC/

        public ActionResult Index()
        {
            ViewBag.BaiHoc = db.BAIHOCs.ToList();
            return View(db.MONHOCs.ToList());
        }

        //
        // GET: /MONHOC/Details/5

        public ActionResult Details(int id = 0)
        {
            MONHOC monhoc = db.MONHOCs.Find(id);
            if (monhoc == null)
            {
                return HttpNotFound();
            }
            return View(monhoc);
        }

        //
        // GET: /MONHOC/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /MONHOC/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MONHOC monhoc)
        {
            if (ModelState.IsValid)
            {
                db.MONHOCs.Add(monhoc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(monhoc);
        }

        //
        // GET: /MONHOC/Edit/5

        public ActionResult Edit(int id = 0)
        {
            MONHOC monhoc = db.MONHOCs.Find(id);
            if (monhoc == null)
            {
                return HttpNotFound();
            }
            return View(monhoc);
        }

        //
        // POST: /MONHOC/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MONHOC monhoc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(monhoc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(monhoc);
        }

        //
        // GET: /MONHOC/Delete/5

        public ActionResult Delete(int id = 0)
        {
            MONHOC monhoc = db.MONHOCs.Find(id);
            if (monhoc == null)
            {
                return HttpNotFound();
            }
            return View(monhoc);
        }

        //
        // POST: /MONHOC/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MONHOC monhoc = db.MONHOCs.Find(id);
            db.MONHOCs.Remove(monhoc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }


        public ActionResult LocTheoLop(int id)
        {

            //ViewBag.MonHoc = db.MONHOCs.ToList();
            //var t = db.LOPs.Where(p => p.ID == id).ToList();
            //ViewBag.baihoc = (from bh in db.BAIHOCs
            //              from l in db.LOPs
            //              from m in db.MONHOCs
            //              where bh.LOPID == l.ID && bh.MONHOCID == m.ID
            //              select new { bh.LOPID, bh.MONHOCID, bh.TenBaiHoc, bh.Link }).ToList();
            var r = db.BAIHOCs.Where(p => p.LOPID == id).OrderByDescending(p => p.MONHOCID).ToList();
            var MonHoc = db.MONHOCs.ToList();
            ViewBag.MonHocs = MonHoc;
            return View(r);
        }

    }
}

BaoCao_Project/Website/MvcApplication1/Controllers/TUYENSINHController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;

namespace MvcApplication1.Controllers
{
    public class TUYENSINHController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /TUYENSINH/

        public ActionResult Index()
        {
            return View(db.TUYENSINHs.ToList());
        }

        //
        // GET: /TUYENSINH/Details/5

        public ActionResult Details(int id = 0)
        {
            TUYENSINH tuyensinh = db.TUYENSINHs.Find(id);
            if (tuyensinh == null)
            {
                return HttpNotFound();
            }
            return View(tuyensinh);
        }

        //
        // GET: /TUYENSINH/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /TUYENSINH/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TUYENSINH tuyensinh)
        {
            if (ModelState.IsValid)
            {
                db.TUYENSINHs.Add(tuyensinh);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tuyensinh);
        }

        //
        // GET: /TUYENSINH/Edit/5

        public ActionResult Edit(int id = 0)
        {
            TUYENSINH tuyensinh = db.TUYENSINHs.Find(id);
            if (tuyensinh == null)
            {
                return HttpNotFound();
            }
            return View(tuyensinh);
        }

        //
        // POST: /TUYENSINH/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TUYENSINH tuyensinh)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tuyensinh).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tuyensinh);
        }

        //
        // GET: /TUYENSINH/Delete/5

        public ActionResult Delete(int id = 0)
        {
            TUYENSINH tuyensinh = db.TUYENSINHs.Find(id);
            if (tuyensinh == null)
            {
                return HttpNotFound();
            }
            return View(tuyensinh);
        }

        //
        // POST: /TUYENSINH/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TUYENSINH tuyensinh = db.TUYENSINHs.Find(id);
            db.TUYENSINHs.Remove(tuyensinh);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BaoCao_Project/Website/MvcApplication1/Controllers/VIDEOController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;

namespace MvcApplication1.Controllers
{
    public class VIDEOController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /VIDEO/

        public ActionResult Index()
        {
            return View(db.VIDEOs.ToList());
        }

        //
        // GET: /VIDEO/Details/5

        public ActionResult Details(int id = 0)
        {
            VIDEO video = db.VIDEOs.Find(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
        }

        //
        // GET: /VIDEO/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /VIDEO/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VIDEO video)
        {
            if (ModelState.IsValid)
            {
                db.VIDEOs.Add(video);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(video);
        }

        //
        // GET: /VIDEO/Edit/5

        public ActionResult Edit(int id = 0)
        {
            VIDEO video = db.VIDEOs.Find(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
        }

        //
        // POST: /VIDEO/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(VIDEO video)
        {
            if (ModelState.IsValid)
            {
                db.Entry(video).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(video);
        }

        //
        // GET: /VIDEO/Delete/5

        public ActionResult Delete(int id = 0)
        {
            VIDEO video = db.VIDEOs.Find(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
        }

        //
        // POST: /VIDEO/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            VIDEO video = db.VIDEOs.Find(id);
            db.VIDEOs.Remove(video);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BaoCao_Project/Website/MvcApplication1/Views/HOCONLINE/Create.cshtml
@model MvcApplication1.Models.HOCONLINE

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Thêm Website</legend>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Ten)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Ten)
            @Html.ValidationMessageFor(model => model.Ten)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Link)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Link)
            @Html.ValidationMessageFor(model => model.Link)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Hinh)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Hinh)
            @Html.ValidationMessageFor(model => model.Hinh)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BaoCao_Project/Website/MvcApplication1/Views/HOCONLINE/Delete.cshtml
@model MvcApplication1.Models.HOCONLINE

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>HOCONLINE</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Ten)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Ten)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Link)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Link)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Hinh)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Hinh)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

BaoCao_Project/Website/MvcApplication1/Views/HOCONLINE/Details.cshtml
@model MvcApplication1.Models.HOCONLINE

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>HOCONLINE</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Ten)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Ten)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Link)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Link)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Hinh)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Hinh)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BaoCao_Project/Website/MvcApplication1/Views/HOCONLINE/Edit.cshtml
@model MvcApplication1.Models.HOCONLINE

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>HOCONLINE</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Ten)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Ten)
            @Html.ValidationMessageFor(model => model.Ten)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Link)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Link)
            @Html.ValidationMessageFor(model => model.Link)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Hinh)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Hinh)
            @Html.ValidationMessageFor(model => model.Hinh)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BaoCao_Project/Website/MvcApplication1/Views/HOCONLINE/Index.cshtml
@model IEnumerable<MvcApplication1.Models.HOCONLINE>

@{
    ViewBag.Title = "Index";
}

<style>
    ul li {
        display: inline;
    }

    a:link {
        color: #000000;
        background-color: transparent;
        text-decoration: none;
    }

    a:visited {
        color: #000000;
        background-color: transparent;
        text-decoration: none;
    }

    a:hover {
        color: #ff0000;
        background-color: transparent;
        text-decoration: underline;
    }

    a:active {
        color: #ff0000;
        background-color: transparent;
        text-decoration: underline;
    }
</style>
<body>

    <div style="padding-left:167px"><h2>Các trang web học online</h2></div>
    <div style="width:1000px; border-top: 4px solid; margin: 0 auto; padding-top: 10px">
        @foreach (var item in Model)
        {
            <a href="@item.Link" target="_blank" style="padding: 10px"><img src="@item.Hinh" /></a>
        }
    </div>

    <div style="padding-left:1130px">@Html.ActionLink("Thêm", "Create")</div>




</body>
<div style="padding-top: 10px;width:1000px; border-bottom: 4px solid; margin: 0 auto;"><h2>@Html.ActionLink("Các môn học", "Index", "MONHOC")</h2></div>
@foreach (MvcApplication1.Models.MONHOC m in ViewBag.MonHoc)
{
    <div style="padding-left: 5px; padding-top:10px; border: 1px solid;height: 50px; width:50px; margin:10px auto 10px 167px">
        <div style="padding-top:10px">@m.TenMonHoc</div>
    </div>
    <div style="width:1000px;margin:0 auto">
        @foreach (MvcApplication1.Models.BAIHOC b in (ViewBag.BaiHoc))
        {
            if (b.MONHOCID == m.ID)
            {
                <a href="@b.Link" target="_blank"><div style="padding-left: 30px">@b.TenBaiHoc</div></a>

            }
        }
    </div>
}
<div style="padding-top: 10px;width:1000px; border-bottom: 4px solid; margin: 0 auto;"><h2>@Html.ActionLink("Video", "Index", "VIDEO")</h2></div>
<div style="padding-left: 180px; padding-top: 10px">
    @foreach (MvcApplication1.Models.VIDEO v in ViewBag.Video)
    {
        @*<a href="@v.Link" target="_blank" style="padding-left: 180px">@v.Title</a>*@
        <iframe style="padding-left: 20px" width="300" height="250" src="//@v.Link" frameborder="0"></iframe>
    }
</div>
<div style="padding-top: 10px;width:1000px; border-bottom: 4px solid; margin: 0 auto;"><h2>@Html.ActionLink("Thông tin tuyển sinh", "Index", "TUYENSINH")</h2></div>
@foreach (MvcApplication1.Models.TUYENSINH t in ViewBag.TuyenSinh)
{
    <div>
        <h3>
            <a href="@t.Link" target="_blank" style="padding-left: 180px">@t.Title</a>
        </h3>
    </div>
}